### ISSUE TITLE
Error when installing package on Windows

### ISSUE THREAD

**Issue by abrissard** [SapienzaNLP/maverick-coref#5]
Hello, 

Congratulations for the great work and your ability to defy recent trends, which is not an easy feat in current NLP research.

I wanted to try your models but ran into an error when installing the provided python package using pip.
1. First I got a decoding error related to the README.md :
```
File "C:\Users\alexi\AppData\Local\Temp\pip-install-xm5qg557\maverick-coref_4e42a280cae3439b87a370507594800a\setup.py", line 6, in <module>
          long_description=open("README.md").read(),
        File "D:\dev\miniconda3\envs\llm-process-generation\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 372: character maps to <undefined>
```

2. Then I tried to install it from source (`git clone` then `pip install -e .`) but ran into the same error. I deleted the content of the README.md file, which solved the problem. However I got a second error when running `pip install -e .`
```
        File "D:\dev\miniconda3\envs\maverick\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\dev\miniconda3\envs\maverick\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "D:\dev\miniconda3\envs\maverick\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

Do I miss a specific step (e.g., the package can be used only on linux), or is it a problem with the package itself ?
I would be very grateful if you could take the time to check my issue as it impact the usability and reproducibility of your work 

### Full error traces (I'm using Windows 11 and this is setup in a new conda environment)
Error 1:
```
pip install maverick-coref
Collecting maverick-coref
  Using cached maverick-coref-1.0.3.tar.gz (41 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\alexi\AppData\Local\Temp\pip-install-xm5qg557\maverick-coref_4e42a280cae3439b87a370507594800a\setup.py", line 6, in <module>
          long_description=open("README.md").read(),
        File "D:\dev\miniconda3\envs\llm-process-generation\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 372: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Error 2:
```
pip install -e .       
Obtaining file:///G:/Mon%20Drive/Code/maverick-coref
  Preparing metadata (setup.py) ... done
Collecting pytorch-lightning>=1.8.0 (from maverick-coref==1.0.3)
  Using cached pytorch_lightning-2.4.0-py3-none-any.whl.metadata (21 kB)
Collecting pandas>=1.3.5 (from maverick-coref==1.0.3)
  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting hydra-core>=1.2 (from maverick-coref==1.0.3)
  Using cached hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting transformers>=4.34 (from maverick-coref==1.0.3)
  Using cached transformers-4.45.1-py3-none-any.whl.metadata (44 kB)
Collecting spacy>=3.7.2 (from maverick-coref==1.0.3)
  Using cached spacy-3.8.2-cp312-cp312-win_amd64.whl.metadata (27 kB)
Collecting jsonlines==4.0.0 (from maverick-coref==1.0.3)
  Using cached jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Collecting sentencepiece==0.1.99 (from maverick-coref==1.0.3)
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\alexi\AppData\Local\Temp\pip-install-djh68_zz\sentencepiece_e7dd841c440a446083eb3a3f0ac15ccd\setup.py", line 126, in <module>
          subprocess.check_call([
        File "D:\dev\miniconda3\envs\maverick\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\dev\miniconda3\envs\maverick\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\dev\miniconda3\envs\maverick\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "D:\dev\miniconda3\envs\maverick\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by IordanisSap** [comment]
How did you solve this?

**Comment by g185** [comment]
Hi guys, thanks for using Maverick! 
I will investigate this problem as soon as possible.
Since it seems a problem due to Windows, I suggest using the Windows subsystem for Linux, [https://learn.microsoft.com/en-us/windows/wsl/install](WSL), in which I already verified the correct working of the repository.

Sorry for the inconvenience,
Giuliano

**Comment by g185** [comment]
@IordanisSap, the first error is, as you mentioned, a common problem on Windows due to the README.md containing utf-8 characters. 
A simple workaround in Windows is deleting the content of the README.md file, or installing the [WSL](https://learn.microsoft.com/en-us/windows/wsl/instal).

**Comment by g185** [comment]
@IordanisSap @abrissard,   After deleting the content of the README.md file, I was able to install the package using the conda package manager, which I suggest you using in general when dealing with a python package installation:

1. Download miniconda: https://docs.anaconda.com/miniconda/install/#quick-command-line-install
2. Open the Anaconda Powershell Prompt
3. Creating a new environment (I tested with python 3.10)
4. install from source

Let me know if this fixes your problems!
Giuliano

**Comment by IordanisSap** [comment]
Just deleting the content of the README.md file solved it for me.
